baseURL = "/"
defaultContentLanguage = "zh-tw"
locale = "zh-tw"
title = "Tech Events Notes"
hasCJKLanguage = true
theme = "hugo-theme-bootstrap"
enableRobotsTXT = true
enableEmoji = true
pygmentsUseClasses = true
disableKinds = ["rss"]

[pagination]
  pagerSize = 10

[build]
  writeStats = true

[params]
  description = "技術會議／活動筆記"
  brand = "Tech Events Notes"
  logo = false
  titleCase = false
  titleSeparator = "-"
  tocWordCount = 1

[params.sidebar]
    fixed = true
    taxonomiesToggle = false

[menu]
  [[menu.main]]
    identifier = "events"
    name = "活動列表"
    url = "/events/"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    lineNos = true
    noClasses = false
    lineNumbersInTable = false
